#!/bin/bash
set -e

export PATH="/usr/local/opt/libiconv/bin:$PATH"
export PATH="/usr/local/opt/ccache/libexec:$PATH"
export LDFLAGS="-L/usr/local/opt/libiconv/lib"
export CPPFLAGS="-I/usr/local/opt/libiconv/include"

autoreconf -vfi

./configure --disable-video --without-qt --without-gtk --disable-nls \
            --with-python=python3 --without-imagemagick --with-graphicsmagick

make
sudo make install
