#!/bin/bash
set -e

PATH=$PATH:/c/tools/msys64/usr/bin/
export CONFIG_SHELL=/usr/bin/bash.exe

autoreconf -vfi

./configure \
    --host=i686-w64-mingw32 \
    --prefix=/usr/local/win32 \
    --with-directshow \
    --without-gtk \
    --without-python \
    --without-qt --without-java \
    --without-imagemagick \
    --enable-pthread --disable-dependency-tracking

# HACK: Ensure that msys64 comes first, as otherwise libtool won't work
PATH=/c/tools/msys64/usr/bin/:$PATH

make
make install
