name: Upload binaries to release

on:
  release:
    types:
      - created
      - published
      - edited

  workflow_dispatch:

permissions:
  contents: write

jobs:
  Ubuntu:
    name: Build for Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v7
    - name: prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build build-essential pkg-config \
                                devscripts debhelper-compat dh-exec \
                                dh-sequence-python3 dh-sequence-meson lftp \
                                libdbus-1-dev libjpeg-dev libmagickwand-dev \
                                libv4l-dev libgtk-3-dev libgtk2.0-dev \
                                libqt5x11extras5-dev qtbase5-dev python3-dev
    - name: Debian package build
      run: |
        .github/workflows/debuilder.sh
        (cd ..; tar czf zbar-ubuntu-22.04.tar.gz *deb)

    - name: upload
      uses: softprops/action-gh-release@v3.0.3
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: ../zbar-ubuntu-22.04.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}

  Mac_OS:
    name: Build for Mac OS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - name: prepare
      run: |
        brew install meson ninja libiconv graphicsmagick python pkg-config ccache
    - name: configure and build
      run: |
        meson setup builddir --prefix=/usr/local -Dvideo=false -Dpython=python3
        meson compile -C builddir
        DESTDIR="$PWD/macos" meson install -C builddir
    - name: generating tarball
      run: |
        DIR="$PWD"
        tar c -C ${PWD}/macos -f ${DIR}/zbar-macos.tar.gz -z .
    - name: upload
      uses: softprops/action-gh-release@v3.0.3
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: ./zbar-macos.tar.gz
        token: ${{ secrets.GITHUB_TOKEN }}

  Windows:
    name: Build for Windows
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, i686]
        include:
          - arch: x86_64
            msystem: MINGW64
          - arch: i686
            msystem: MINGW32
    defaults:
      run:
        shell: msys2 {0}

    env:
      CPPFLAGS: -D__USE_MINGW_ANSI_STDIO=1

    steps:
    - uses: msys2/setup-msys2@v2.32.0
      with:
        msystem: ${{ matrix.msystem }}
        update: false
        install: >-
          mingw-w64-${{ matrix.arch }}-gcc
          base-devel git zip
          meson
          ninja
          pkgconf

    - uses: actions/checkout@v7

    - name: configure and build
      shell: msys2 {0}
      run: |
        meson setup builddir --prefix=/usr -Dvideo=false -Dgtk=no -Dpython=no -Dqt=false -Djava=disabled -Dimagemagick=disabled -Ddbus=disabled -Dpthread=true
        meson compile -C builddir
    - name: generating zip
      shell: msys2 {0}
      run: |
        DESTDIR=${PWD}/win_${{ matrix.arch }} meson install -C builddir
        (cd ${PWD}/win_${{ matrix.arch }}; zip -r ../zbar-win_${{ matrix.arch }}.zip .)

    - name: upload
      uses: softprops/action-gh-release@v3.0.3
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: ./zbar-win_${{ matrix.arch }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
